### ISSUE TITLE
Add support for treeherder

### ISSUE THREAD

**Issue by sethfowler** [gkoberger/BugzillaJS#101]
Mozilla is migrating from tbpl to treeherder for try jobs. It'd be great to have treeherder jobs inlined the way try jobs are now.

**Comment by Rik** [comment]
People will post URLs like this in Bugzilla: https://treeherder.mozilla.org/#/jobs?repo=%s&revision=%s
And we should include an iframe like this https://treeherder.mozilla.org/resultset-status/<repository>/<revision>/

**Comment by edmorley** [comment]
Almost, it's:
https://treeherder.mozilla.org/embed/resultset-status/{repository}/{revision}/

**Comment by sethfowler** [comment]
@Rik, it looks like bug 1115904 is resolved. So what's left to do here? Just update BugzillaJS itself?

**Comment by sethfowler** [comment]
(This has become much more urgent for me now that try pushes no longer even give you a TBPL URL.)

**Comment by Rik** [comment]
We need a patch yes. As soon as we have one, I'll submit it to AMO on the following week-end.

**Comment by MikeRatcliffe** [comment]
@Rik You have a patch ;)

**Comment by Rik** [comment]
I couldn't review it this week-end but I'll do it as soon as my workday is over tonight ;)

**Comment by Rik** [comment]
Sorry for the delay, I couldn't review yesterday. Will schedule again for tomorrow evening.

**Comment by Rik** [comment]
The new version is waiting for review. https://addons.mozilla.org/en-US/firefox/addon/bugzillajs/versions/ if you want it early.
