### ISSUE TITLE
make default values configurable

### ISSUE THREAD

**Issue by allstarschh** [gkoberger/BugzillaJS#113]
There are many fancy features in this add-on,
however for some features they are default to off, and some default to on.
Also in the preference page there's no way to configure it.
So I have to do this manually by every tab.

**Comment by Rik** [comment]
The add-on does provide a way to configure which features are enabled so I'm not sure what this bug is about. Can you be more specific?

**Comment by allstarschh** [comment]
Did you mean the 'BugzillaJS Preferences' on top of the Bugzilla page?
If so then perhaps I met another bug,
I cannot reproduce for now, but I do have a couple times I need to change the settings 'per tab'. (I have refreshed the page, but the settings for the tab doesn't change)
I'll close this one for now, sorry for the noise.
