### ISSUE TITLE
Relative dates broken against bugzilla 5.0?

### ISSUE THREAD

**Issue by djzort** [gkoberger/BugzillaJS#115]
Our bugzilla 4.0 install has just been upgraded to 5.0.

With the "Turn timestamps into relative dates" option turned on, dates on comments are now:

"NaN years, NaN months ago"

With it off, they are like "2015-04-22 14:19:32 AEST"

Relative dates worked correctly before upgrading bugzilla.

**Comment by yfdyh000** [comment]
3.4.1-signed works for me on https://landfill.bugzilla.org/bugzilla-tip/.

**Comment by djzort** [comment]
landfil 5.0 is fine for me too... how very strange

**Comment by djzort** [comment]
seems ok on our internal 5.0 bugzilla install. closing.
