### ISSUE TITLE
Read me doesn't contain instructions to install on chrome. 

### ISSUE THREAD

**Issue by dyaniv** [gkoberger/BugzillaJS#119]
Can you please add this info or provide manual steps to allow using BugzillaJS on Chrome?

**Comment by yfdyh000** [comment]
Why do you think this extension is compatible with Chrome browser?

**Comment by dyaniv** [comment]
It uses Omnium that should work in chrome (or any other browser) and I have seen more than one report on people using it in chrome. I might be wrong and it doesn't, but I would add that to the readme as well.

**Comment by yfdyh000** [comment]
Well, it looks really may support for Chrome, sorry for the noise.
However, it is likely not working properly for now, like #103.

**Comment by gkoberger** [comment]
I wrote both BugzillaJS and Omnium, like, 5 years ago. Omnium/BugzillaJS did at one point support Chrome, but since Bugzilla is only really used by Mozillians, I'm not sure if it's still working at all.
