### ISSUE TITLE
comment dates are broken if language is not English (e.g. German)

### ISSUE THREAD

**Issue by DirkSchmitt** [gkoberger/BugzillaJS#124]
If I use the german localization the date on comments are broken:
NaN years, NaN months ago

If I switch to english the rendering is ok.

A feasible solution would be to use the original (localized) date instead the broken rendered text.

**Comment by mnoorenberghe** [comment]
I removed the relative date support in version 4.0.0 because it's buggy and some bugzilla installations already support this.
