### ISSUE TITLE
Not e10s compatible...

### ISSUE THREAD

**Issue by albill** [gkoberger/BugzillaJS#128]
BugzillaJS is disabled on current nightly and will be disabled for all users when Firefox 57 ships. Any chance of an update to allow it to continue to work?

**Comment by mnoorenberghe** [comment]
Hi Al,

I've been planning to post to find out what features of this extension are still valuable now that many things have been upstreamed. I doubt I'll have time to port the whole extension anytime soon but if only a few of the modules were still useful then it's possible I could port them sooner.

If anyone else wants to take over this extension that's also an option.

I'm going to close this in favour of #69 but I'm still interested in hearing which features are useful.

**Comment by albill** [comment]
Is there a breakdown of the things Bugzilla JS does/did that are now rolled into Bugzilla? I've noticed some on Mozilla's Bugzilla but haven't ever thought about the entire feature set.
