### ISSUE TITLE
configuration of server in V4.1.0 for Firefox

### ISSUE THREAD

**Issue by HaraldHoe** [gkoberger/BugzillaJS#129]
How can I configure by Bugzilla server in version 4.1.0 for Firefox?
There is no settings button in the add-on overview.

Best regards,
Harald

**Comment by mnoorenberghe** [comment]
This wasn't possible with the new extension API until recently but it's not an easy transition. Does it not work on an installation you want? Or do you want to disable it on one? If you give me the URL I can make it work.

**Comment by HaraldHoe** [comment]
On a computer with an updated version of BugzillaJS it is working.
But I want to install it on a new computer.

In about:config I found on the working computer the entry:
extensions.jid0-NgMDcEu2B88AbzZ6ulHodW9sJzA@jetpack.urls

Does it work if I create this entry on the new computer?
I tried but may I did something wrong because it does not work.

**Comment by mnoorenberghe** [comment]
There is currently no setting to control the domains this runs on, only some hard-coded patterns.

Go the the preferences for the extension in the add-ons manager (they just moved there and out of the Bugzilla page) and ensure that the features you are expecting are checked.

**Comment by HaraldHoe** [comment]
Thank you.
After re-installation of the add-on it is working.
