### ISSUE TITLE
Add option to use (custom) fields instead of whiteboard values

### ISSUE THREAD

**Issue by tooh** [gkoberger/BugzillaJS#57]
Option to choose if you want to use whiteboard field or (custom) fields.

In our installation we have added a custom field Sprint.
Perhaps also support for Theme and Epic fields.

Why not use assignee field instead of u=[user] ?
Why not use component field instead of or additional to c= ?

**Comment by Rik** [comment]
Closing this as I have no intention to support Bugzilla agile going forward.
