### ISSUE TITLE
Remove features upstreamed in Bugzilla

### ISSUE THREAD

**Issue by rik** [gkoberger/BugzillaJS#63]
I asked glob to identify features that have been upstreamed into Bugzilla:
- [x] "Show all changes to the bug inline"
- [x] "Remove "Bug" from the title, so it's easier to see the bug number with a lot of tabs" remove, already upstream
- [x] "Automatically select component and product for "Clone Bug" link"  remove, already upstream
- [x] "Add a "File It" box to the new bug page" is now included on our Bugzilla.

**Comment by darkred** [comment]
[**@Rik**](https://github.com/Rik) commented on [Nov 5, 2012, 5:12 PM GMT+2](https://github.com/gkoberger/BugzillaJS/issues/63#issue-8107312 "2012-11-05T15:12:00Z - Replied by Github Comment Enhancer"):
> I asked glob to identify features that have been upstreamed into Bugzilla:
> 
> *   [X] "Show all changes to the bug inline"
> *   [X] "Remove "Bug" from the title, so it's easier to see the bug number with a lot of tabs" remove, already upstream
> *   [X] "Automatically select component and product for "Clone Bug" link"  remove, already upstream
> *   [X] "Add a "File It" box to the new bug page" is now included on our Bugzilla.

Suggestion: to update the `Features` list in https://addons.mozilla.org/el/firefox/addon/bugzillajs/ 
removing the mention to the above 4 features.
