### ISSUE TITLE
Settings are not remembered

### ISSUE THREAD

**Issue by fwenzel** [gkoberger/BugzillaJS#68]
Not sure why, but I keep switching on "Don't guess OS and Hardware" and every time I file a new bug, it's back to its default behavior, until I switch that setting back on.

The add-on does not actually seem to remember its settings.

**Comment by mnoorenberghe** [comment]
With the switch to a Web Extension, which also syncs your settings if you're logged in to a Firefox Account, I hope this will be solved.
