### ISSUE TITLE
Convert to a WebExtension

### ISSUE THREAD

**Issue by rik** [gkoberger/BugzillaJS#69]
I don't think anyone is using this with Chrome. I haven't tested in Chrome once and no one is pushing a build anywhere on the web.

Removing the Ominum abstraction will make debug easier and might also let us add features that go outside the page.

I'll let this bug open for a few weeks and if no one complains, I'll drop support.

**Comment by mnoorenberghe** [comment]
At this point I think it makes sense to convert to a WebExtension and then we get Chrome, Edge, and Opera support along with Firefox.

**Comment by cvan** [comment]
👍 agreed 100%. takers?

**Comment by yfdyh000** [comment]
Working on https://github.com/yfdyh000/BugzillaJS/tree/WebExtension.
Is making options popup to make it works and debug in Google Chrome.

**Comment by yfdyh000** [comment]
I found a options popup may not be necessary, due to "Your extension's content scripts can directly access user data without the need for a background page." on https://developer.chrome.com/extensions/storage#type-StorageArea. And an Options (preferences) tab (page) may be better.

However, I did not find a way to debugging the content scripts broken in Google Chrome.

**Comment by mnoorenberghe** [comment]
@yfdyh000 I would very much prefer merging/reviewing small, focused commits so feel free to open pull requests

**Comment by yfdyh000** [comment]
@mnoorenberghe Feel free to take and improves them, I don't have the experience for perfection and publishing them.

**Comment by marsjaninzmarsa** [comment]
Any up?

**Comment by mnoorenberghe** [comment]
I just submitted [v4.0.0](https://github.com/gkoberger/BugzillaJS/releases/tag/v4.0.0) to AMO which is an embedded Web Extension so it can migrate settings from the add-on SDK.

Version 4.1.0 will be a plain web extension and compatible with Fx57.

**Comment by mnoorenberghe** [comment]
* Version 4.0.1 was approved this morning and is an embedded web extension to convert preferences to the web extension storage
* Version 4.1.0 was just approved for users running 57+ as a regular web extension

Force an update check in the add-on manager if you want to get the updates in the correct order (mostly for users not yet running 57+)
