### ISSUE TITLE
Please list features missing relative to "Bugzilla Tweaks"

### ISSUE THREAD

**Issue by SamB** [gkoberger/BugzillaJS#92]
You say that this "contains almost all features Bugzilla Tweaks has", but you don't say which ones are missing.  It would be nice if you would expand on this by adding a list of features that (a given version of) Bugzilla Tweaks has that are still missing from BugzillaJS.  (This would probably help the indecisive user conclude: "Oh, I don't really care about those features anyway, BugzillaJS it is.")

**Comment by mnoorenberghe** [comment]
Bugzilla Tweaks was last updated 4 years ago (Jun 28, 2013) so I don't think this is important anymore.
