### ISSUE TITLE
Date approximations are off for recent comments

### ISSUE THREAD

**Issue by lmandel** [gkoberger/BugzillaJS#96]
BugzillaJS's date approximations are sometimes pretty far off on recent comments. For ex, bug 974857 comment 26 current shows "1 week ago" but the comment was added on Sep 5 (it is currently Sep 19), which is 2 full weeks ago. I also see the issue with reported days with BugzillaJS displaying "1 day ago" for a comment that was posted on Sep 17 and "2 days ago" for a comment posted on Sep 16. I would like to see the estimation get better. This may be as simple as changing the ranges that BugzillaJS uses for estimation. I would guess that BugzillaJS will currently only state 1 day after 24 hours has passed and 1 week after 168 hours have passed. Here are suggested changes to the ranges:

1 day > 20 hours
2 days > 42 hours
1 week > 5 days
2 weeks > 11 days
etc.

**Comment by mnoorenberghe** [comment]
I removed the relative date support in version 4.0.0 because it's buggy and some bugzilla installations already support this.
